---
- name: Common | Update apt cache
  sudo: yes
  apt: update-cache=yes
  tags: common

- name: Common | Install System Packages
  sudo: yes
  apt: pkg={{ item }} state=installed
  with_items: system_packages
  tags: common