---
openssh:
    server:
        config:
            - { name: password_authentication, value: "no" }
            - { name: permit_root_login, value: "no" }
            - { name: allow_tcp_forwarding, value: "no" }
            - { name: permit_tunnel, value: "no" }
            - { name: authorized_keys_file, value: "%h/.ssh/authorized_keys" }
            - { name: challenge_response_authentication, value: "no" }
            - { name: use_p_a_m, value: "yes" }
            - { name: subsystem, value: "sftp /usr/lib/openssh/sftp-server" }