Ecwec\Bundle\WeatherDataProviderBundle\Entity\Station:
    type: entity
    table: null
    repositoryClass: Ecwec\Bundle\WeatherDataProviderBundle\Entity\StationRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        objectId:
            type: string
            length: 255
            column: object_id
        name:
            type: string
            length: 255
        description:
            type: text
        latitude:
            type: float
            length: 255
        longitude:
            type: float
            length: 255
    lifecycleCallbacks: {  }
